const data = {
    products: [
        {
            _id:'1',
            name: 'Dock Station',
            category:'Dock',
            image: '/image/dock.png',
            price: 1290,
            countInStock: 10,
            brand:'China',
            rating: 2,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'2',
            name:'cable',
            category:'Cables',
            image: '/image/cable.png',
            price: 190,
            countInStock: 18,
            brand:'China',
            rating:3.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'3',
            name:'Dock Station',
            category:'Dock',
            image: '/image/egpu imagem.jpg',
            price: 390,
            countInStock: 102,
            brand:'China',
            rating:4,
            numReviews:190,
            description: 'high quality product',
        },
        {
            _id:'4',
            name:'Dock Station',
            category:'Dock',
            image: '/image/dock.png',
            price: 390,
            countInStock: 20,
            brand:'Duda',
            rating:4.0,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'5',
            name:'Power Supply',
            category:'Acessories',
            image: '/image/power suply.png',
            price: 690,
            countInStock: 55,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'6',
            name:'Dock Station',
            category:'Dock',
            image: '/image/dock.png',
            price: 390,
            countInStock: 30,
            brand:'Asus',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
    ],
};

export default data;