import bcrypt from 'bcryptjs';

const data = {
    users: [
        {
            name:'Leandro',
            email:'lecamilotti@gmail.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: true,
        },
        {
            name:'Thais',
            email:'user@example.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: false,
        },
    ],
    products: [
        {
            _id:'1',
            name: 'Dock Station',
            category:'Dock',
            image: '/image/dock.png',
            price: 1290,
            countInStock: 0,
            brand:'China',
            rating: 3.5,
            numReviews:9,
            description: 'high quality product',
        },
        {
            _id:'2',
            name:'cable',
            category:'Cables',
            image: '/image/cable.png',
            price: 190,
            countInStock: 18,
            brand:'China',
            rating:3.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'3',
            name:'Dock Station',
            category:'Dock',
            image: '/image/cable.png',
            price: 390,
            countInStock: 102,
            brand:'China',
            rating:4,
            numReviews:190,
            description: 'high quality product',
        },
        {
            _id:'4',
            name:'Dock Station',
            category:'Dock',
            image: '/image/dock.png',
            price: 390,
            countInStock: 20,
            brand:'Duda',
            rating:4.0,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'5',
            name:'Power Supply',
            category:'Acessories',
            image: '/image/cable.png',
            price: 690,
            countInStock: 1,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'6',
            name:'Dock Station',
            category:'Dock',
            image: '/image/dock.png',
            price: 390,
            countInStock: 30,
            brand:'Asus',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
    ],
};

export default data;