const data = {
    products: [
        {
            _id:'1',
            name: 'Dock Station',
            category:'Dock',
            Image: '/image/dock.png',
            price: 390,
            brand:'China',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'2',
            name:'cable',
            category:'Cables',
            Image: '/image/cable.png',
            price: 190,
            brand:'China',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'3',
            name:'Dock Station',
            category:'Dock',
            Image: '/image/egpu imagem.jpg',
            price: 390,
            brand:'China',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'4',
            name:'Dock Station',
            category:'Dock',
            Image: '/image/dock.png',
            price: 390,
            brand:'Duda',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'5',
            name:'Power Supply',
            category:'Acessories',
            Image: '/image/power suply.png',
            price: 690,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'6',
            name:'Dock Station',
            category:'Dock',
            Image: '/image/dock.png',
            price: 390,
            brand:'Asus',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
    ],
};

export default data;